source 'https://rubygems.org'

gem 'sinatra'
gem 'slim'
gem 'rest-client'
gem 'addressable'

group :development do
  gem 'rack-test', require: 'rack/test'
  gem 'rspec', require: %w(rspec rspec/core/rake_task)
  gem 'cucumber', require: 'cucumber/rake/task'
  gem 'page_magic', '1.0.0.alpha3'
  gem 'watir-webdriver'
  gem 'shotgun'
  gem 'simplecov'
  gem 'waitforit'
  gem 'childprocess'
  gem 'thin'
  gem 'wait'
  gem 'rake'
  gem 'webmock'
  gem 'timecop', '~> 0.8.0'
end