source 'https://rubygems.org'

gem 'oauth'
gem 'json'
gem 'sinatra'
gem 'hashie'
gem 'slim'
gem 'dotenv'

group :development do
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
  gem 'webmock'
  gem 'capybara'
  gem 'watir-webdriver'
end