require 'rake'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

Dir.glob('lib/ruby_bootcamp/rake/*.rake').each { |r| import r }

task default: [:spec, :rubocop]

desc 'Run tests'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
end

desc 'Run rubocop'
RuboCop::RakeTask.new(:rubocop) do |task|
  task.options << '--auto-correct'
end